version: '3'

services:
  cartographer:
    image: but5gera/era_5g_cartographer:0.1.0
    volumes:
      - ~/tmp/shared_dir:/root/shared_dir
    environment:
      - ROS_DOMAIN_ID=77
    networks:
      - my_network

  relay_server1:
    image: but5gera/ros2_relay_server_slam:1.3.0
    environment:
      - ROS_DOMAIN_ID=77
      - NETAPP_PORT=5897
      - 'TOPICS_FROM_CLIENT=[{"name": "/out/draco", "type": "point_cloud_interfaces/msg/CompressedPointCloud2"}, {"name": "/robot/odometry/filtered", "type": "nav_msgs/msg/Odometry"},{"name": "/robot/imu/data", "type": "sensor_msgs/msg/Imu", "qos": {"preset": "SENSOR_DATA"}},{"name": "/clock", "type": "rosgraph_msgs/msg/Clock", "qos": {"preset": "SENSOR_DATA"}}]'
      - 'TRANSFORMS_TO_CLIENT=[{"source_frame": "robot/odom", "target_frame": "map", "angular_thres": 0.1, "trans_thres": 0.001, "max_publish_period": 0.01 }]'
      - 'SERVICES_FROM_CLIENT=[{"name": "finish_mapping", "type": "std_srvs/srv/Trigger"}, {"name": "start_mapping", "type": "era_5g_interfaces/srv/TriggerMap"}, {"name": "start_localization", "type": "era_5g_interfaces/srv/TriggerMap"}, {"name": "stop_localization", "type": "std_srvs/srv/Trigger"}]'

    ports:
      - 5897:5897
    networks:
      - my_network
