version: '3'

services:
  client1:
    image: but5gera/ros2_relay_client_slam:1.3.0
    environment:
      - ROS_DOMAIN_ID=44
      - NETAPP_ADDRESS=http://localhost:5897
      - SEND_CLOCK=True
      - 'TOPICS_TO_SERVER=[{"name": "/robot/odometry/filtered", "type": "nav_msgs/msg/Odometry"},{"name": "/robot/imu/data", "type": "sensor_msgs/msg/Imu", "qos": {"preset": "SENSOR_DATA"}}, "qos": {"preset": "SENSOR_DATA"}}]'
    network_mode: host

  client2:
    image: but5gera/ros2_relay_client_slam:1.3.0
    environment:
      - ROS_DOMAIN_ID=44
      - NETAPP_ADDRESS=http://localhost:5898
      - 'TOPICS_TO_SERVER=[{"name": "/robot/top_laser/point_cloud", "type": "sensor_msgs/msg/PointCloud2", "compression": "draco"}]'
      - 'TOPICS_FROM_SERVER=[{"name": "/map", "type": "nav_msgs/msg/OccupancyGrid"}]'
    network_mode: host

  client3:
    image: but5gera/ros2_relay_client_slam:1.3.0
    environment:
      - ROS_DOMAIN_ID=44
      - NETAPP_ADDRESS=http://localhost:5899
      - 'TRANSFORMS_TO_SERVER=[{"source_frame": "robot/base_footprint", "target_frame": "robot/odom", "angular_thres": 0.1, "trans_thres": 0.001, "max_publish_period": 0.01 }, { "source_frame": "robot/imu_link", "target_frame": "robot/base_footprint", "angular_thres": 0.1, "trans_thres": 0.001, "max_publish_period": 0.01 }, { "source_frame": "robot/top_laser_link", "target_frame": "robot/base_footprint", "angular_thres": 0.1, "trans_thres": 0.001, "max_publish_period": 0.01}]'
      - 'SERVICES_TO_SERVER=[{"name": "finish_mapping", "type": "era_5g_interfaces/srv/TriggerMap"}, {"name": "start_mapping", "type": "std_srvs/srv/Trigger"}, {"name": "start_localization", "type": "era_5g_interfaces/srv/TriggerMap"}, {"name": "stop_localization", "type": "std_srvs/srv/Trigger"}]'
    network_mode: host

